### ISSUE TITLE
MAC Firewall question is repeatedly asked when running UI tests on iOS simulators

### ISSUE THREAD

**Issue by jpc1963** [calabash/DeviceAgent.iOS#310]
I run UI tests on iOS & Android simulators. They (and the apps I test) are created in Xamarin. The tests are run on a Mac.
When I run a test on iOS, the following question is asked:
Do you want the application “DeviceAgent-Runner.app” to accept incoming network connections?

This is asked each time I run a test. I always click “Allow” but still the question will be asked again the next time.
If I check the firewall options I see DeviceAgent-Runner.app listed. But this is a tremporary file. When I run the test again, a new file is generated in a different directory and the question is asked again.

My firewall is ON (I have no control over this).
But on my older Mac, if I turn the firewall OFF, the question is not asked.

**Comment by jmoody** [comment]
Hey.  I saw the original report you posted on the Visual Studio (?) site. 

I understand the problem.  The only suggestion I can give is to try to use `pfctl` to allow traffic on specific port.  I don't have experience with this so I cannot provide any guidance.

We cannot sign the DeviceAgent app with a macOS developer certificate because the iOS Simulator would reject the app at install or the app would crash at launch on the simulator.

I think I saw a third-party firewall tool that sits on top of the macOS firewall that will allow you manage access by ports (instead of trying to figure out how use `pfctl`).  The port to open is `27753`.

**Comment by jpc1963** [comment]
I had forgotten about this but I solved it (more or less) by solving a similar problem related to the firewall. 

The solution can be found here:
[https://tomsoderling.github.io/Disable-iOS-simulator-connections-popup/](url)

**Comment by jmoody** [comment]
Great.  Thanks for the link.

**Comment by LeoJHarris** [comment]
@jpc1963 having the same issue and that link is dead...
